#+title: Dot Emacs Bankruptcy
#+date: [2023-09-28 Thu]
#+lastmod: [2025-01-14 Tue]
#+tags[]: Emacs
#+draft: false

I started using Emacs in 2015 during my first year of university, likely with version 25.1. It's hard to believe that it's been nearly a decade since I began my journey with this powerful tool. Over the years, I’ve experienced a couple of "dot-emacs bankruptcies," where my configurations became too cumbersome and inefficient. But this time, things are different.

In my early attempts, I experimented with all sorts of configurations, adding every new Elisp function and macro inside my Emacs just trying new stuff and failing to make all work together. However, the result was chaos - startup times creeping up to two minutes and barely anything working.

The second attempt was more informed but still fell short. With a more mature view of my Emacs usage and a better understanding of elisp to know what was going on I tried a new configuration. However, the result was bad but better than the privious time. I thought I knew what was going on but clearly I didn't.

Now, on my third iteration. I removed everything unecessary. It is the best minimal and modular configuration I could use. But in my current job requires me to use using Windows instead of Linux, my configuration is suboptimal. The majority of the config expects some unix programs to run and Windows does not support them. In fact, my Emacs setup is no longet optimized for my workflow.

So that is the reason for my dot emacs bankruptcy. To adequate my config for this new environment. Also to try to document some of the elisp code inside my config. Because even though I've been using it for 8 years there is so much more to learn, discover and master with this incredibly versatile editor.

* Current Configuration
:PROPERTIES:
:Created:  2023-09-28
:END:

I use a method to tangle specific source code blocks inside orgmode files and extract them to a ".el" file so that Emacs can read only these and possibilly compile them to be faster.

The configuration is separated in these files

#+begin_src text

   elisp
   init-backup.org
   init-basicConfig.org
   init-bookmark.org
   init-buffer-menu.org
   init-completion.org
   init-customFunctions.org
   init-denote.org
   init-elgrep.org
   init-flycheck.org
   init-fun.org
   init-grep.org
   init-hydra.org
   init-ibuffer.org
   init-ivy.org
   init-keyBinding.org
   init-ledger.org
   init-magit.org
   init-orgmode.org
   init-orgmode-packages.org
   init-playground.org
   init-programming.org
   init-setup-package.org
   init-spellcheck.org
   init-themes.org
   init-words.org
   init-yasnippet.org

#+end_src

An init-emacs.org file is tangled first to create the base configuration that loads all the other parts.

* Dream Configuration
:PROPERTIES:
:Created:  2023-09-28
:END:

Trim all the unused parts and simplify adding/improving modules in the future. Learn more about each part making it easier to share my dot emacs with others.

I don't know if the best way to create the configuration file is to tangle different parts of an org mode inside the files or just create all the modules in elisp format and comment/remove the unecessary parts. Then create a more detailed org just to describe what was created at that moment.
